Review
OwlusMain/HSEHashMap pull request #1
Opened 2019-03-15 17:30 UTC by OwlusMain

Шморгунов Александр
Группа БПМИ-183

[Ссылка на сабмит в ЯК](https://official.contest.yandex.ru/contest/11654/run-report/19636845/)

2019-03-23 18:08 UTC, Skird requested changes

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +#include <utility>
1) стоит использовать include guards
2) правило хорошего тона: держать свой код в namespace, чтобы не засорять глобальный

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +const int TABLESIZE = 5e5;
1) для таких констант неплохо подходит static constexpr - это гарантирует, что значение будет подставлено на этапе компиляции и не войдет во все translation units, раздувая размер библиотечных и испоняемых файлов
2) хеш-таблицы фиксированного большого размера это не юзабельно (для задач норм, но типа если кто-то этот код захочет реюзнуть, то ему будет плохо). Надо предусмотреть механизм авторасширения, благо тут это не очень сложно

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +        MapElement(std::pair<KeyType, ValueType> newVal, size_t index = 0, MapElement* nextEl = nullptr, MapElement* prevEl = nullptr) :
Конструктор, который может принимать один параметр всегда стоит отмечать explicit (в тех редких случаях, когда не стоит, лучше написать прямо явно /* implicit */ и комментарий оставить, зачем и почему)

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +    constexpr HashMap(const Hash& hasher_obj = Hash()) : hashArray(TABLESIZE), hasher(hasher_obj) {}
constexpr конструктор конечно неплохо, но он еще должен быть и explicit

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +    template<typename Ptr>
Правило хорошего тона: указывать в typename, с каким итератором готова работать структура (InputIterator, ForwardIterator, etc)

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +    HashMap(const std::initializer_list<std::pair<const KeyType, ValueType>>& elements, const Hash& hasher_obj = Hash()) :
Копипаста. А можно просто делегировать этот конструктор предыдущему

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +        while (first != last) {
Не очень понятно, почему тут так, а не просто в цикле делать insert?

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +    const_iterator cSt, cFin;
Как-то не очень выглядит хранить тут внутри эти итераторы. Из-за них еще и копирование/move осложнены
Лучше будет хранить указатель на первый и последний элемент мапы и из них вычислять begin(), end(), cbegin(), cend(). А еще лучше будет вообще не писать двусвязный список руками и завести человеческий std::list

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +    HashMap& operator= (const HashMap& other) {
Надо переделать логику хранения связного списка и
1) либо убрать этот оператор присваивания (потому что дефолтный итак неплохо скопирует поля)
2) либо реализовать дополнительно move c-tor/move assignment. Потому что из-за этого оператора компилятор не может их сам сгенерировать и тип становится не Movable. А можно бы было нахаляву сделать Moveable

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +    void erase(const KeyType key) {
Хорошо бы предусмотреть какой-то механизм сжатия таблицы при удалении, чтобы не занимать много лишней памяти
Либо вести себя как вектор, предоставить метод типа shrink_to_fit чтобы можно было вручную память чистить, если сильно надо

2019-03-23 18:08 UTC, Skird commented on amic5.cpp
> +        size_t curHash = hasher(key) % TABLESIZE;
Этот цикл скопипащен минимум 4 раза. 2 из них видимо по делу, там реально трудно по-другому сделать, а вот тут можно воспользоваться find() уже написанным явно

2019-03-29 11:53 UTC, OwlusMain commented
Я изменил реализацию хешмапы, теперь она работает через list значений и хеш массив итераторов на элементы листа.
Поэтому итераторы получилось использовать не свои, а для листа.

Также добавил динамическое расширение/уменьшение массива (чтобы нормально амортизированно работало, уменьшается он, если число элементов меньше в 4 раза, а увеличивается, если в 2)


Дам новую [ссылку на ЯК](https://official.contest.yandex.ru/contest/11654/run-report/19811084/), т.к. решение сильно поменялось

2019-03-29 14:22 UTC, Skird approved these changes

2019-03-29 14:22 UTC, merged